idx: 450
erasor: 
    max_range: 60.0
    num_rings: 15
    num_sectors: 108 # 108
    min_h: -1.3 # [m] Note that it depends on the distance between body frame and ground contact point of mobile robots
    max_h: 3.0 # [m] Note that it depends on the distance between body frame and ground contact point of mobile robots
    th_bin_max_h: 0.2 # [m]
    scan_ratio_threshold: 0.2 # percentage: originally, 0.3 yet 0.3 seems like it is quite aggressive!
    minimum_num_pts: 6
    rejection_ratio: 0
    gf_dist_thr: 0.15 # originally, 0.125
    gf_iter: 3
    gf_num_lpr: 10
    gf_th_seeds_height: 0.5
    version: 3 # 2: R-GPF / 3: R-GPF w/ blocking (not in paper)



MapUpdater:
    data_type: "01"
    initial_map_path: "/media/shapelim/UX960NVMe1/kitti_semantic/semantic_KITTI_map/src_v2/01_150_to_250_w_interval1__voxel_0_2.pcd"
    env: "outdoor"
    save_path: "/media/shapelim/UX960NVMe1/kitti_semantic/semantic_KITTI_map/erasor_v2"
    query_voxel_size: 0.2
    map_voxel_size: 0.2 
    voxelization_interval: 10
    removal_interval: 1

sensors_on:
    is_odom_on: true
    is_pc2_on: true

tf:
     lidar2body: [0.0, 0.0, 1.73, 0, 0.0, 0.0, 1.0] # xyz q_x, q_y, q_z, q_w in order

verbose: true
    


